version: "1.0"

services:
  api:
    container_name: connect-api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app # bind mount current dir for development

  postgres:
    container_name: connect-postgresql
    image: postgres:latest
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: connect-redis
    image: redis:latest
    restart: no
    ports:
      - 6379:6379

  pgadmin:
    container_name: connect-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 3000:80
    depends_on:
      - postgres

  redis-commander:
    container_name: connect-redis-commander
    image: rediscommander/redis-commander:latest
    restart: no
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8081:8081

volumes:
  pgdata:
